---
- name: create VM from Template
  hosts: kvm-nodes
  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: create disk from template
      command: >
               cp "{{ vm_location }}/templates/{{ template_name }}" "{{ vm_location}}/{{ vm_name }}.{{ vm_disk_type }}"
      when: vm_name not in disks.stdout

    - name: get list of VMs
      virt:
        command: "list_vms"
      register: vms

    - name: create vm
      command: >
                virt-install --import --name "{{ vm_name }}"
                --memory "{{ vm_memory }}" --vcpus "{{ vm_cpus }}"
                --disk "{{ vm_location }}/{{ vm_name }}.{{ vm_disk_type }}"
                --noautoconsole --os-variant linux2020
                --network network=default,link.state=true --network network=host-bridge,link.state=true
      when: vm_name not in vms.list_vms

    - name: start vm
      virt:
        name: "{{ vm_name }}"
        state: running
        
    - name: Get First Admin IP Address from VM
      command: uvt-kvm ip "{{ vm_name }}"
      register: vm_ip
      until: vm_ip is success
      retries: 5
      delay: 10

    - name: Set Stats for VM IP
      set_stats:
        data: 
          vm_ip: "{{ vm_ip.stdout }}"
