---
- name: create VMs
  hosts: kvm-nodes
  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: create disk
      command: >
               virt-builder --format qcow2 {{ item.value.template_name }} --hostname {{ item.value.hostname}}
               -o {{ vm_location}}/{{ item.value.name }}.{{ item.value.file_type }}
               --root-password password:{{ root_pass }}
      when: item.value.name not in disks.stdout
      with_dict: "{{ guests }}"

    - name: get list of VMs
      virt:
        command: "list_vms"
      register: vms

    - name: create vm
      command: >
                virt-install --import --name {{ item.value.name }}
                --memory {{ item.value.mem }} --vcpus {{ item.value.cpus }}
                --disk {{ vm_location }}/{{ item.value.name }}.{{ item.value.file_type }}
                --noautoconsole --os-variant {{ item.value.os_type }}
      when: item.value.name not in vms.list_vms
      with_dict: "{{ guests }}"

    - name: start vm
      virt:
        name: "{{ item.value.name }}"
        state: running
      with_dict: "{{ guests }}"
