---
- name: Create VMs
  hosts: kvm-nodes
  tasks:
  - name: shutting down vm
    virt:
      name: "{{ item.key }}"
      state: shutdown
    with_dict: "{{ guests }}"

  - name: deleting vm
    virt:
      name: "{{ item.key }}"
      command: "undefine"
    with_dict: "{{ guests }}"

  - name: deleting vm disks
    file:
      path: "{{ vm_location}}/{{ item.key }}.{{ item.value.file_type }}"
      state: absent
    with_dict: "{{ guests }}"
