---
- name: Create VMs
  hosts: kvm-nodes
  tasks:
  - name: shutting down vm
    community.libvirt.virt:
      name: "{{ item.value.name }}"
      state: shutdown
    with_dict: "{{ guests }}"

  - name: deleting vm
    community.libvirt.virt:
      name: "{{ item.value.name }}"
      command: "undefine"
    with_dict: "{{ guests }}"

  - name: deleting vm disks
    file:
      path: "{{ vm_location}}/{{ item.value.name }}.{{ item.value.file_type }}"
      state: absent
    with_dict: "{{ guests }}"
