---
- name: create VM
  hosts: kvm-nodes
  gather_facts: false
  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: create disk
      command: >
               virt-builder "{{ template_name }}" --format "{{ vm_disk_type }}" --hostname "{{ vm_hostname }}"
               -o "{{ vm_location}}/{{ vm_name }}.{{ vm_disk_type }}"
               --root-password password:{{ root_pass }}
      when: vm_name not in disks.stdout

    - name: get list of VMs
      community.libvirt.virt:
        command: "list_vms"
      register: vms

    - name: create vm
      command: >
                virt-install --import --name "{{ vm_name }}"
                --memory "{{ vm_memory }}" --vcpus "{{ vm_cpus }}"
                --disk "{{ vm_location }}/{{ vm_name }}.{{ vm_disk_type }}"
                --noautoconsole --os-variant linux2020
      when: vm_name not in vms.list_vms

    - name: start vm
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: running
