---
- name: Create VMs
  hosts: kvm-nodes
  tasks:
  - name: shutting down vm
    virt:
      name: "{{ vm_name }}"
      state: shutdown

  - name: deleting vm
    virt:
      name: "{{ vm_name }}"
      command: "undefine"

  - name: deleting vm disks
    file:
      path: "{{ vm_location}}/{{ vm_name }}.{{ vm_disk_type }}"
      state: absent
